# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moko < Formula
  desc "CLI for querying Deutsche Bahn real-time transit information with interactive TUI"
  homepage "https://github.com/mobil-koeln/moko-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mobil-koeln/moko-cli/releases/download/v0.1.0/moko-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "1b0deda1d9640fde15d87b8976dc14e0a0dccae0df7f009e73c06b52d249e963"

      def install
        bin.install "moko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mobil-koeln/moko-cli/releases/download/v0.1.0/moko-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "1d3f1d3280ee33e376be01825b2e74f5afa76e9b05e85421b1ac09fddbee4bb7"

      def install
        bin.install "moko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mobil-koeln/moko-cli/releases/download/v0.1.0/moko-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "e47e9fc4bb9e88f469e7ee5a6c2f5c64be98e81d25beafa2c6a0539eaeaf45ac"
      def install
        bin.install "moko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mobil-koeln/moko-cli/releases/download/v0.1.0/moko-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "dc5e6fdcf4d65883c75fa4350388fa4fe170acf237dec0b09445a7692f56c0d3"
      def install
        bin.install "moko"
      end
    end
  end

  test do
    system "#{bin}/moko", "--version"
  end
end
