# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moko < Formula
  desc "CLI for querying Deutsche Bahn real-time transit information with interactive TUI"
  homepage "https://github.com/mobil-koeln/moko-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mobil-koeln/moko-cli/releases/download/v0.4.0/moko-cli_0.4.0_darwin_amd64.tar.gz"
      sha256 "511cb27aaa580b00ebf312ee89c3df39e0b566bd690b154e4bf5dc2c94bfc882"

      define_method(:install) do
        bin.install "moko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mobil-koeln/moko-cli/releases/download/v0.4.0/moko-cli_0.4.0_darwin_arm64.tar.gz"
      sha256 "aba1e52ae8f0bb6204ceb86b12124f2b65d0472b284b947eb6138caeae978913"

      define_method(:install) do
        bin.install "moko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mobil-koeln/moko-cli/releases/download/v0.4.0/moko-cli_0.4.0_linux_amd64.tar.gz"
      sha256 "7293778569f221f939c7fcad149aee42cf2f710c0d33353599a8943618c409c5"
      define_method(:install) do
        bin.install "moko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mobil-koeln/moko-cli/releases/download/v0.4.0/moko-cli_0.4.0_linux_arm64.tar.gz"
      sha256 "65f3ac5bb418aaf462c3f3250e2a96e70a9f252a0242144925d2ba85f38bd7c6"
      define_method(:install) do
        bin.install "moko"
      end
    end
  end

  test do
    system "#{bin}/moko", "--version"
  end
end
